version: '3.8'

services:
  pincode_uikit_mfe:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3050:3000"
    networks:
      - pincode_uikit_mfe_network

networks:
  pincode_uikit_mfe_network:
    driver: bridge